### ISSUE TITLE
stdin ?

### ISSUE THREAD

**Issue by Wafelack** [ritiek/rust-without-rust#1]
We can't use stdin with that code.

**Comment by ritiek** [comment]
Hi. Yes, probably not. It's been a long time since I wrote this and this isn't really being maintained. I'm not even sure what the current state of the tool is.

**Comment by Wafelack** [comment]
Ok thx, if you want I reused part of your code in [my rust discord bot](https://github.com/Wafelack/ferribot). 😁

Thx anyway
